[package]
name = "sv_watcher"
version = "0.1.0"
authors = ["lorran <lorran@sixcreative.com.br>"]
edition = "2018"

[dependencies]
reqwest ="0.9"
actix-web = "1.0"
askama = "0.8"
log = "0.4.0"
env_logger = "0.7.1"

[build-dependencies]
askama = "0.8"